- name: Find the task I want
  snow_record:
    username: ansible_test
    password: my_password
    instance: dev38191
    table: sc_task
    lookup_field: number
    number: SCTASK0010002
    state: present
  tags: test
  register: mytask

- name: Find the linux machines
  snow_record_find:
    username:  ansible_test
    password: my_password
    instance: dev38191
    table: cmdb_ci_linux_server
    query_field: os
    query_string: 'Linux Red Hat'
    return_fields:
      - sys_id
  tags: test
  register: cis

- name: Attach some stuff
  snow_record:
    username: ansible_test
    password: my_password
    instance: dev38191
    table: task_ci
    state: present
    data:
      task: "{{mytask.record['sys_id']}}"
      ci_item: "{{item['sys_id']}}"
  with_items:
    - "{{cis.record}}"
  tags: test

- name: Goof off
  snow_record_find:
    username: ansible_test
    password: my_password
    instance: dev38191
    table: task_ci
    query_field: sys_id
    query_string: 2d8723d9db6c4300c791fe1ebf961941
  tags: test

- name: Search for incident assigned to group, return specific fields
  snow_record_find:
    username: ansible_test
    password: my_password
    instance: dev38191
    table: incident
    query_field: assignment_group
    query_string: d625dccec0a8016700a222a0f7900d06
    return_fields:
      - number
      - opened_at
  tags: find

- name: Grab a user record
  snow_record:
    username: ansible_test
    password: my_password
    instance: dev38191
    state: present
    number: 62826bf03710200044e0bfc8bcbe5df1
    table: sys_user
    lookup_field: sys_id

- name: Create an incident
  snow_record:
    username: ansible_test
    password: my_password
    instance: dev38191
    state: present
    data:
      short_description: "This is a test incident opened by Ansible"
      severity: 3
      priority: 2
  register: new_incident

- name: Delete the record we just made
  snow_record:
    username: admin
    password: ADMINPASS
    instance: dev38191
    state: absent
    number: "{{new_incident['record']['number']}}"
  tags: hi
  failed_when: false
  ignore_errors: true

- name: Delete a non-existant record
  snow_record:
    username: ansible_test
    password: my_password
    instance: dev38191
    state: absent
    number: 9872354
  failed_when: false

- name: Update an incident
  snow_record:
    username: ansible_test
    password: my_password
    instance: dev38191
    state: present
    number: INC0000055
    data:
      work_notes : "Been working all day on this thing."

- name: Attach a file to an incident
  snow_record:
    username: ansible_test
    password: my_password
    instance: dev38191
    state: present
    number: INC0000055
    attachment: README.md
  tags: attach
